# 
# ETH Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.4 $
# $Date: 1993/02/01 22:30:21 $


FILES = eth
DIRS =

include $(MAKE_INCLUDE)/Makefile.common
