#
# $RCSfile: Makefile,v $
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.3 $
# $Date: 1993/02/02 00:54:46 $
#

DIRS = netipc socket
FILES =

XRT=../..
LIB=libPxk_$(HOW)

OBJECTFILE = newObjectList

include $(MAKE_INCLUDE)/Makefile.lib
