#
# $RCSfile: Makefile,v $
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.6 $
# $Date: 1993/02/03 18:44:49 $
#

DIRS = 
FILES = mach-full-convert mach-xfer machnetipc port-maint ssr hdr-utils

WARNINGS =

CFLAGS := $(CFLAGS) -DPORTLOCKS -DMAKESENDCOUNT -DNOMORESENDERS

include $(MAKE_INCLUDE)/Makefile.common
