# 
# Test protocol Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.5.1.1 $
# $Date: 1993/02/02 22:34:44 $


FILES = chantest ethtest iptest icmptest tcptest udptest xrpctest 
DIRS =

include $(MAKE_INCLUDE)/Makefile.common

