#
# drivers Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.8 $
# $Date: 1993/02/01 23:52:49 $
#

DIRS = eth
FILES =

include $(MAKE_INCLUDE)/Makefile.common


