#
# $RCSfile: Makefile,v $
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.2 $
# $Date: 1993/02/01 22:33:37 $
#

DIRS = 
FILES = rrx rrx_hdr srx srx_hdr xfer
INCLUDES := $(INCLUDES) -I$(XRT)/mach3/netipc

include $(MAKE_INCLUDE)/Makefile.common
