#
# Mach Operating System
# Copyright (c) 1993-1988 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie Mellon 
# the rights to redistribute these changes.

# HISTORY
# $Log:	Makefile,v $
# Revision 2.4  94/06/29  15:01:25  mrt
# 	Updated for odemake.
# 	[94/02/16            mrt]
# 
# Revision 2.3  90/10/29  17:26:19  dpj
# 	Cleaned-up installation rules.
# 	[90/10/27  17:46:00  dpj]
# 
# 	Cleaned-up installation rules.
# 	[90/10/21  21:16:06  dpj]
# 
# Revision 2.2  90/07/26  12:35:57  dpj
# 	First version
# 	[90/07/24  14:22:31  dpj]
# 
#
######################################################################


VPATH			= ../../mach3
INCFLAGS		= -I../../mach3

CONFIGURATION		= MACH3_US

TARGET_NAME		= ../libmach3_us.a

.include "../../mach3/Makefile-include"

