# 
# ARP Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.11 $
# $Date: 1993/02/01 22:18:57 $


FILES = arp arp_table arp_$(XPLATFORM)
DIRS =

include $(MAKE_INCLUDE)/Makefile.common

