# 
# CHAN Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.5 $
# $Date: 1993/02/01 22:30:48 $
#
	
FILES = chan chan_client chan_server chan_debug chan_mapchain
DIRS =

include $(MAKE_INCLUDE)/Makefile.common
