#
# Makefile.lib
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.10 $
# $Date: 1993/02/01 23:58:56 $
#
#
# Libary Makefile -- this is the equivalent of Makefile.common but
# modified slightly for libraries

MAKEFILE=Makefile

SRC = $(addsuffix .c,$(FILES))
LIBPREFIX = $(LIB)(
LIBSUFFIX = .o)
OBJ = $(addprefix $(LIBPREFIX), $(addsuffix $(LIBSUFFIX), $(FILES)))


.PHONY : pxk depend clean

default:
	rm -f $(OBJECTFILE) ; \
	make lib

lib: $(OBJ)
	@$(MAKE) LOOP TARGET=
	@if [ -s $(OBJECTFILE) ]; then \
		echo rebuilding library ; \
		umask 2 ; \
		ar ruv $(LIB) `/bin/cat $(OBJECTFILE)` ; \
		rm -f $(OBJECTFILE) ; 				\
		echo randomizing library ; \
		ranlib $(LIB) ; \
	else \
		true ; \
	fi ; 


#SRCLIST HDRLIST:
#	rm -f $(OBJECTFILE) ; 
#	@$(MAKE) LOOP TARGET=$@


clean: localclean
	rm -f $(LIB)
	@make LOOP TARGET=$@


SRCLIST HDRLIST depend dotodirs: %: local%
ifeq ($(DIRS),)
	@true
else
	@$(MAKE) LOOP TARGET=$@
endif


include $(MAKE_INCLUDE)/Makefile.local


# generic loop target called by other targets
LOOP:
	@for dir in $(DIRS) ; do \
		echo $$dir ; \
		cd $$dir ; \
		$(MAKE) $(TARGET)  XRT:=../$(XRT) LIB:=../$(LIB) \
			OBJECTFILE:=../$(OBJECTFILE).$$$$ ; \
		cd .. ; \
		if [ -s $(OBJECTFILE).$$$$ ]; then \
			cat -s $(OBJECTFILE).$$$$ | fixRelPaths $$dir >> $(OBJECTFILE) ; \
			rm -f $(OBJECTFILE).$$$$ ; \
		fi ; \
	 done ; \
	true


include Makedep.$(HOW)
