#
# Mach3 platform Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.9 $
# $Date: 1993/02/02 00:01:18 $
#

DIRS = netipc socket drivers pxk
FILES =

XRT=..
LIB=libPxk_$(HOW)

OBJECTFILE = newObjectList

include $(MAKE_INCLUDE)/Makefile.lib
