# 
# SUNRPC Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.6 $
# $Date: 1993/02/01 22:28:40 $

	
FILES = sunrpc sunrpc_client sunrpc_ctl sunrpc_error sunrpc_hdr sunrpc_server xrpc_callmsg xrpc_print xrpc_prot 
DIRS =


include $(MAKE_INCLUDE)/Makefile.common
