#
# sunos platform Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.11 $
# $Date: 1993/02/01 23:52:44 $
#

DIRS = drivers pxk
FILES = 

XRT=..
LIB=libPxk_$(HOW)

OBJECTFILE = newObjectList

include $(MAKE_INCLUDE)/Makefile.lib

