#
# $RCSfile: Makefile,v $
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.1 $
# $Date: 1993/02/02 00:55:00 $
#

DIRS = test
FILES =

include $(MAKE_INCLUDE)/Makefile.common
