# 
# Mach Operating System
# Copyright (c) 1993-1988 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie Mellon 
# the rights to redistribute these changes.
#  
#
# File:        Makefile
#
# HISTORY: 
# $Log:	Makefile,v $
# Revision 2.7  94/06/29  15:03:29  mrt
# 	Updated for odemake. Removed history
# 	[93/11/28            mrt]
# 
# Revision 2.5  91/11/06  14:17:43  jms
# 	Don't build "nfs" by default
# 	[91/11/04  17:42:04  jms]
# Revision 2.2  90/08/22  18:13:38  roy
# 	First version.
# 	[90/08/22  12:04:49  roy]
# 
#
#


EXPINC_SUBDIRS		= tty
SUBDIRS			= diag name tm as ufs tty pipenet config net
#SUBDIRS		= diag name tm as ufs tty nfs pipenet config net

.include <${RULES_MK}>

