.TH AS_PASSWORD 3 8/2/88
.CM 4
.SH NAME
as_change_password \- changes a user's password
.SH SYNOPSIS
.B #include <mach.h>
.br
.B #include <auth_defs.h>
.PP
.B kr = as_change_password(server_port, private_port, user_name,
.B old_pass_word, new_pass_word)
.br
.B kern_return_t kr;
.br
.B port_t server_port;
.br
.B port_t private_port;
.br
.B group_name_t user_name;
.br
.B pass_word_t old_pass_word;
.br
.B pass_word_t new_pass_word;
.SH DESCRIPTION
.I as_change_password
changes the password stored by the authentication service for the user
.I user_name
to be
.I new_pass_word.
For the change to be permitted either the
.I private_port
passed in the call must represent the system administrator, who is allowed
to change any user's password, or the
.I private_port
must represent the user requesting the password change and the
.I old_pass_word
must be correct.
.PP
The
.I server_port
parameter must be the authentication server's public service port.
.SH "SEE ALSO"
as_group(3),
as_list(3),
as_login(3),
as_token(3),
as_translate(3)
.SH HISTORY
.TP 
02-Aug-88  Robert Sansom (rds) at Carnegie-Mellon University
Created.
