# 
# VCACHE Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.3 $
# $Date: 1993/02/01 22:36:00 $
#
	
FILES = vcache
DIRS =

include $(MAKE_INCLUDE)/Makefile.common
