#
# sim_ether makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#


FILES = sim_ether
DIRS =

INCLUDES := $(INCLUDES) -I../../../protocols/eth

include $(MAKE_INCLUDE)/Makefile.common


