# 
# BIDCTL Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.2 $
# $Date: 1993/02/01 22:36:56 $
	

FILES = bidctl bidctl_state bidctl_timer bidctl_id
DIRS = 


include $(MAKE_INCLUDE)/Makefile.common
