#
# ether makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.7 $
# $Date: 1993/02/02 00:01:44 $

FILES = ether
DIRS =

INCLUDES := $(INCLUDES) -I../../../protocols/eth

CFLAGS := $(CFLAGS) -DTEST_TYPE_FILTER

include $(MAKE_INCLUDE)/Makefile.common


