# 
# ICMP Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.6 $
# $Date: 1993/02/01 22:21:39 $
#


FILES = icmp icmp_reqrep
DIRS =

INCLUDES := $(INCLUDES) -I../ip

include $(MAKE_INCLUDE)/Makefile.common

