#
# Mach Operating System
# Copyright (c) 1993-1988 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie Mellon 
# the rights to redistribute these changes.

# File:        Makefile
#
# HISTORY:
# $Log:	Makefile,v $
# Revision 2.3  94/06/29  15:00:57  mrt
# 	Updated for Odemake
# 	[94/04/20  13:49:47  mrt]
# 
# Revision 2.2  91/11/06  11:28:59  jms
# 	Created.
# 	[91/09/26  18:46:52  pjg]
# 
#

DEPENDENCIES	=
CONFIGURATION	= ${MACH3_CONFIGURATION:UMACH3_US}

EXPDIR		= /us/lib/
EXPLIB_TARGETS	= export_libc++.a
IDIR		= /us/lib/
ILIST		= libc++.a

LIBRARIES	= libc++.a
OFILES		= gnulib3.o xyzzy.o

.include <${RULES_MK}>
