#
# IP Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.12 $
# $Date: 1993/02/01 22:21:58 $
#


FILES = ip iproute ip_gc ip_control ip_util ip_hdr ip_frag ip_rom ip_input
DIRS =

include $(MAKE_INCLUDE)/Makefile.common
