#
# pi Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.15 $
# $Date: 1993/02/01 23:57:22 $
#

DIRS = idmap
FILES = msg hoststr list netmask part prottbl prottbl_parse sessn_gc upi upi_defaults xk_debug event_monitor rwlock

XRT=..
LIB=libPi_$(HOW)

OBJECTFILE = newObjectList


include $(MAKE_INCLUDE)/Makefile.lib

