#
# Mach Operating System
# Copyright (c) 1993-1988 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie Mellon 
# the rights to redistribute these changes.

# HISTORY
# $Log:	Makefile,v $
# Revision 2.4  94/06/29  15:01:42  mrt
# 	Updated for odemake
# 	[94/02/09            mrt]
# 
# Revision 2.3  90/10/29  17:26:37  dpj
# 	Cleaned-up installation rules.
# 	[90/10/27  17:46:49  dpj]
# 
# 	Cleaned-up installation rules.
# 	[90/10/21  21:16:46  dpj]
# 
# Revision 2.2  90/07/26  12:36:12  dpj
# 	First version
# 	[90/07/24  14:23:16  dpj]
# 
#
######################################################################

CONFIGURATION		= MACH3_VUS

VPATH			= ../../mach3
INCFLAGS		= -I../../mach3


TARGET_NAME		= ../libmach3_vus.a
LOC_TARGET_NAME		= libmach3_vus.a
EXPLIB_TARGETS		= export_libmach3_vus.a
EXPORTBASE		= ./
EXPDIR			= ../

.include "../../mach3/Makefile-include"

