# 
# UDP Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.7 $
# $Date: 1993/02/01 22:28:36 $
	

FILES = udp udp_port
DIRS = 

#
# ../util picks up the port management code
#
INCLUDES := $(INCLUDES) -I../util

include $(MAKE_INCLUDE)/Makefile.common
