/* 
 * compose.h
 *
 * x-kernel v3.2
 *
 * Copyright (c) 1993,1991,1990  Arizona Board of Regents
 *
 *
 * $Revision: 1.3 $
 * $Date: 1993/02/01 23:57:01 $
 */

/* 
 * Prototypes of functions generated by compose
 */


#ifndef compose_h
#define compose_h

/* 
 * This is a bit of a kludge.  The mselect protocol links in code
 * which uses the traceselectp variable, but compose will generate use
 * of the tracemselectp variable.
 */
#define tracemselectp	traceselectp

extern 	char *protocolTables[];

void	build_pgraph_dev( void );
void	build_pgraph( void );
void	initTraceLevels( void );


#endif ! compose_h
