#
# pxk Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.12.1.2 $
# $Date: 1993/02/02 03:26:25 $
#

DIRS = 
FILES = alloc input_process event init ocsum process time trace utils 

include $(MAKE_INCLUDE)/Makefile.common
