# 
# $RCSfile: Makefile,v $
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
#
# $Revision: 1.2 $
# $Date: 1993/02/01 22:38:09 $
	

FILES = vdrop
DIRS = 


include $(MAKE_INCLUDE)/Makefile.common
