#
# idmap makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.4 $
# $Date: 1993/02/01 23:56:04 $

FILES = idmap
DIRS =

include $(MAKE_INCLUDE)/Makefile.common

