# 
# Mach Operating System
# Copyright (c) 1993-1988 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie Mellon 
# the rights to redistribute these changes.
#  
# Purpose:  build netserver/xkernel utility software
# 
# HISTORY
# $Log:	Makefile,v $
# Revision 2.3  94/07/19  18:39:55  mrt
# 		Updated for odemake.
# 	[94/07/19            mrt]
# 
# Revision 2.2  94/01/11  18:10:46  jms
# 	Initial Version
# 	[94/01/10  13:12:30  jms]
# 
# Revision 2.4  92/07/05  23:34:01  dpj
# 	No further changes.
# 	[92/06/29  23:08:16  dpj]
# 
# 	Fixed to compile "compose" as a straight UNIX program (not MACH3_VUS),
# 	so that it will run on a 2.6 system.
# 	[92/03/12  13:55:17  dpj]
# 
# Revision 2.3  92/03/05  15:10:55  jms
# 	Configuration MACH3_UNIX => MACH3_VUS
# 
# Revision 2.2  90/10/29  18:11:57  dpj
# 	Integration into master source tree
# 	[90/10/21  22:55:49  dpj]
# 
# 	First working version.
# 	[90/10/03  22:01:09  dpj]
# 
#
######################################################################

SUBDIRS			= compose

.include  <${RULES_MK}>
