# 
# VMUX Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.2 $
# $Date: 1993/02/01 22:33:32 $
	

FILES = vmux
DIRS = 


include $(MAKE_INCLUDE)/Makefile.common
