#
# drivers Makefile
#
# x-kernel v3.2
#
# Copyright (c) 1991  Arizona Board of Regents
#
# $Revision: 1.5 $
# $Date: 1991/10/30 00:51:57 $
#

DIRS = eth
FILES =

include $(MAKE_INCLUDE)/Makefile.common

